# Generated by Django 3.1.7 on 2021-03-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('measurement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tea_type', models.CharField(max_length=30)),
                ('ingredients', models.CharField(default='', max_length=30)),
                ('origin', models.CharField(default='Unknown', max_length=30)),
            ],
        ),
    ]
