# Generated by Django 3.0.5 on 2021-04-02 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('measurement', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tea_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gre', 'Green Tea'), ('Bla', 'Black Tea'), ('Whi', 'White Tea'), ('Jas', 'Jasmine'),
                                                   ('Ool', 'Oolong'), ('Mat', 'Matcha'), ('Cha', 'Chai'), ('Roo', 'Rooibos'), ('Her', 'Herbal'), ('Fru', 'Fruit')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('origin', models.CharField(default='Unknown', max_length=30)),
                ('ingredients', models.ManyToManyField(to='main_app.Ingredients')),
                ('tea_type', models.ManyToManyField(to='main_app.Tea_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tea')),
            ],
        ),
    ]
