# Generated by Django 3.0.5 on 2021-04-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='date',
            field=models.DateField(verbose_name='drink date'),
        ),
    ]
