# Generated by Django 3.0.5 on 2021-04-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210402_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
